### ISSUE TITLE
The linkHelper seems to have a problem

### ISSUE THREAD

**Issue by carlosguedes** [tanas57/MROS#1]
Hello Sir. How are you? I'm testing your application but it seems that when the app tries to fetch information from: https://mros.api.muslu.net/v1/

It doesn't exists. 

Can you help me solve this?

**Comment by carlosguedes** [comment]
I'm trying running inside the AVD.

**Comment by tanas57** [comment]
Hello, thanks.

Yes, This application fetches data from a web API. You must run an API program that is WebAPI/MROS_API. It is a .net core project. Deploy and run this project and then change API URL in LinkHelper.java.
And try again.

Thanks.

**Comment by carlosguedes** [comment]
Thank you very much Tanas. One more question: What strings i need to generate the QR code?

**Comment by carlosguedes** [comment]
Do you have an email that i can reach you? Would like to make a proposition about this project. Thanks in advance

**Comment by tanas57** [comment]
> Thank you very much Tanas. One more question: What strings i need to generate the QR code?

I don't remember :) I am sorry.  But it seems like that restaurant-id in DB :)
Actually you find it in source code. For example;

case FETCH_RESTAURANT_WITH_TABLE:
                result = API_URI + "table/" + qrcode;
                break;

I think this string is "Tables DB ID" :) would you control it?

**Comment by tanas57** [comment]
You can reach my contact address in below link. 
https://www.muslu.net/iletisim

**Comment by carlosguedes** [comment]
Ive sent you an email. Thanks!
